### ISSUE TITLE
a question about PositionalEmbedding module

### ISSUE THREAD

**Issue by watchwater** [jiwidi/Behavior-Sequence-Transformer-Pytorch#4]
Helo，thanks for your complete code. I read this code carefully，and have a question. 

It's BST model's forward function 
```
transfomer_features, user_features, target_movie_rating = self.encode_input(batch)
transfomer_features = self.positional_embedding(transfomer_features)
```
And it's positional_embedding module
```
class PositionalEmbedding(nn.Module):
    def __init__(self, max_len, d_model):
        super().__init__()

        self.pe = nn.Embedding(max_len, d_model)

    def forward(self, x):
        batch_size = x.size(0)
        return self.pe.weight.unsqueeze(0).repeat(batch_size, 1, 1)
```
we can see that PositionalEmbedding do nothing, just return it's weight.  PositionalEmbedding doesn't have any interaction with **x**. It's really confused.

**Comment by jiwidi** [comment]
Hi! Thanks for the question, let me try answer it

Is exactly just returning the weight of the positional embedding, weight is the actual value of the embeddings.

Since we are using a fixed sequence length and we are creating positional embeddings for positions==max_len we will want the full weight of the positional embedding table.

So for max_len=10 the positional embedding table will have 10 entries right?? We want to access those 10 entries and sum the value of those entries to the already existing sequence items (we are doing sum of positional embedding here, not concat)

**Comment by watchwater** [comment]
Hello, thanks for your patient and detailed explanation, I will read code again with the help of this explanation.

**Comment by shamanez** [comment]
```
    
    def forward(self, batch):
        transfomer_features, user_features, target_movie_rating = self.encode_input(batch)
        transfomer_features = self.positional_embedding(transfomer_features)
        transformer_output = self.transfomerlayer(transfomer_features)
        transformer_output = torch.flatten(transformer_output,start_dim=1)
```

According to the above function, you only input the positional encoding to the **transformer layer**.  Because the output from self.positional_embedding is actually an embedding lookup.   I think you need an extra step to add  transfomer_features, with positional encodings before sending it through the transformer layer.
