### ISSUE TITLE
How did you decide on nn.linear(661, 1024)?

### ISSUE THREAD

**Issue by dogdoghua** [jiwidi/Behavior-Sequence-Transformer-Pytorch#8]
I wonder where 661 comes from.

thanks.

**Comment by guccialex** [comment]
661 is the square root of the amount of unique movies hard coded in, so that the input to the transformer can match the shape of the output of the embedding.
I'm not sure why the decision was made, but you can see the output shape of the movie embeddings
` nn.Embedding(   len(movies.year.unique()), int(math.sqrt(len(movies.year.unique())))  )`
you can replace it with   int(math.sqrt(len(movies.year.unique())))   and it should fix the errors if you change the dataset size

**Comment by jiwidi** [comment]
```python
def forward(self, batch):
        transfomer_features, user_features, target_movie_rating = self.encode_input(batch)
        positional_embedding = self.positional_embedding(transfomer_features)
        transfomer_features = torch.cat((transfomer_features, positional_embedding), dim=2)
        transformer_output = self.transfomerlayer(transfomer_features)
        transformer_output = torch.flatten(transformer_output,start_dim=1)
        
        #Concat with other features
        features = torch.cat((transformer_output,user_features),dim=1)

        **output = self.linear(features)**
        return output, target_movie_rating
```

Its the shape that the features vector will have before going into the linear layers, its actually hard coded and should be done programatically so its not clear, sorry for that!

**Comment by dogdoghua** [comment]
thanks for your explaination, it's very clear!
